apiVersion: v1
kind: Namespace
metadata:
  name: school-management
  labels:
    name: school-management
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
