apiVersion: v1
kind: Service
metadata:
  name: sms-frontend
  namespace: school-management
  labels:
    app: sms-frontend
    tier: web
spec:
  type: ClusterIP
  selector:
    app: sms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
